version: "2"
name: ak-test-stack-03
canonical: ak-test-stack-03
author: alan_king
description: infra import
image: ""
keywords:
    - ak test keywords
    - provider:aws
template: false
template_ignore: []
technologies: []
dependencies: []
config:
    default:
        name: default
        pipeline:
            pipeline:
                path: pipeline/default/terraform-pipeline.yaml
            variables:
                destination: ($ project $)/($ environment $)/pipeline/variables-($ component $).yml
                path: pipeline/default/variables.sample.yaml
        terraform:
            ak-test-stack-03:
                destination: ($ project $)/terraform/($ environment $)/($ component $)/ak-test-stack-03.tf
                path: terraform/default/ak-test-stack-03.tf.sample
